ChatsApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/reset/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *



app_name = 'main'

urlpatterns = [
    path('', chat_list, name='chat_list'),
    path('chat/<int:pk>/', chat, name='chat'), 
    path('delete_chat/<int:pk>/', delete_chat, name='delete_chat'),
    path('delete_message/<int:pk>/', delete_message, name='delete_message'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login', loginUser, name='login'),
    path('logout', logoutUser, name='logout'),
    path('register', register, name='register'),
    path('user_profile', user_profile, name='user_profile'),
    path('edit_profile', edit_profile, name='edit_profile'),
    path("password-reset/", password_reset_request, name="password-reset"),
    path('change-password/',
         CustomPasswordChangeView.as_view(),
         name='change_password'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
import datetime


# Create your models here.
class User(AbstractUser):
    username = models.CharField(unique=True,
                             max_length=200,
                             null=True,
                             verbose_name='username')
    email = models.EmailField(unique=True,
                                 max_length=200,
                                 verbose_name='email address')
    profile_picture = models.ImageField(default='images/avatar.svg',
                                        upload_to='images/',
                                        null=True,
                                        blank=True)
    is_online = models.BooleanField(default=False)
    last_seen = models.DateTimeField(null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def read_message(self, message) -> None:
        if self.username == message.chat.user:
            message.read = True
        else:
            message.read1 = True
        message.save()

    def __str__(self) -> str:
        return self.username


class ChatManager(models.Manager):

    def create(self, **kwargs):
        user = kwargs['user']
        user1 = kwargs['user1']
        test = Chat.objects.filter(user=user, user1=user1)
        test1 = Chat.objects.filter(user=user1, user1=user)
        if test.exists()  or test1.exists() > 0:
            raise ValidationError('This chat already exists')
        elif not User.objects.filter(
                username=user).exists() or not User.objects.filter(
                    username=user1).exists():
            raise ValidationError(
                'One or both users are not registered on ChatsApp')
        else:
            return super().create(**kwargs)


class Chat(models.Model):
    user = models.CharField(max_length=200)
    user1 = models.CharField(max_length=200)

    def get_other(self, request):
        user_list = [self.user, self.user1]
        return user_list[user_list.index(request.user.username) - 1]

    def user_unread(self):
        user = User.objects.get(username=self.user1)
        return self.messages.filter(read=False, user=user).count()

    def user1_unread(self):
        user = User.objects.get(username=self.user)
        return self.messages.filter(read1=False, user=user).count()

    def get_last_message(self):
        return self.messages.all().last()

    other = None
    other_pic = None
    user_unread_ = None

    def __str__(self) -> str:
        return f"{self.user} | {self.user1}"

    objects = ChatManager()


class Message(models.Model):
    body = models.TextField()
    chat = models.ForeignKey(Chat,
                             on_delete=models.CASCADE,
                             related_name='messages')
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    read = models.BooleanField(null=True, default=False)
    read1 = models.BooleanField(null=True, default=False)
    is_deleted = models.BooleanField(default=False)

    message_margin = '20px'

    def get_user(self):
        return self.chat.user

    def get_user1(self):
        return self.chat.user1

    def __str__(self) -> str:
        if len(self.body) <= 50:
            return self.body
        elif len(self.body) > 50:
            return f"{self.body[:20]}..."

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from main.models import User
from django.forms import ModelForm
from django import forms


class UserCreateForm(UserCreationForm):
    password1 = forms.CharField(help_text='Create a password',
                                label='Enter Password',
                                widget=forms.PasswordInput())

    password2 = forms.CharField(help_text='',
                                label='Confirm password',
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserForm(ModelForm):
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput({
                                 'autofocus': True,
                                 'placeholder': 'Email',
                                 'class': 'form-control'
                             }))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput({
                                   'placeholder':
                                   'Password',
                                   'class':
                                   'form-control'
                               }))

    class Meta:
        model = User
        fields = ['email', 'password']


class UserEditForm(ModelForm):
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={
            'autofocus': True,
            'class': 'form-control',
            'placeholder': 'Email'
        }))
    username = forms.CharField(label='Username',
                            widget=forms.TextInput({
                                'placeholder': 'Username',
                                'class': 'form-control'
                            }))

    class Meta:
        model = User
        fields = ['username', 'email']

users/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth import login, logout, authenticate, views as auth_views
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from .forms import *
from .models import *
from main.models import Chat, User

import datetime

# User = settings.AUTH_USER_MODEL


# Create your views here.
def loginUser(request):
    page = "login"
    if request.user.is_authenticated:
        return redirect("main:chat_list")
    form = UserForm()
    if request.method == "POST":
        email = str(request.POST.get("email")).lower()
        password = request.POST.get("password")
        try:
            user = User.objects.get(username=email)
        except:
            user = None

        in_user = authenticate(username=email, password=password)

        if in_user is not None:
            login(request, in_user)
            return redirect('main:chat_list')
        else:
            if user is None:
                messages.error(request, 'The user does not exist')
            else:
                messages.error(request, 'Your password is incorrect')
    context = {"form": form, "page": page}
    return render(request, "login.html", context)


def logoutUser(request):
    request.user.is_online = False
    request.user.last_seen = datetime.datetime.now()
    request.user.save()
    logout(request)
    return redirect('users:login')


def register(request):
    page = "register"
    form = UserCreateForm()
    if request.method == "POST":
        form = UserCreateForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.profile_picture = request.FILES.get('profile_picture')
            user.save()
            login(request, user)
            return redirect("main:chat_list")

    context = {
        "form": form,
        "page": page,
    }
    return render(request, "register.html", context)


def user_profile(request):
    user = request.user
    chats = [
        chat for chat in Chat.objects.all()
        if request.user.email in [chat.user, chat.user1]
    ]

    try:
        pic = user.profile_picture.url
    except:
        pic = '../static/images/avatar.svg'

    for chat in chats:
        chat.other = chat.get_other(request)

    context = {'chat_number': len(chats), 'pic': pic}
    return render(request, 'user_profile.html', context)


def edit_profile(request):
    user = request.user
    all_chats = Chat.objects.all()
    chats_one = [chat for chat in all_chats if request.user.email == chat.user]
    chats_two = [
        chat for chat in all_chats if request.user.email == chat.user1
    ]

    form = UserEditForm(instance=user)
    if request.method == 'POST':
        email = request.POST.get('email')
        form = UserEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            if request.FILES.get('profile_picture'):
                user.profile_picture = request.FILES.get('profile_picture')
            user = form.save()
            for chat in chats_one:
                chat.user = email
                chat.save()
            for chat in chats_two:
                chat.user1 = email
                chat.save()
            return redirect('main:chat_list')

    context = {'form': form}
    return render(request, 'edit_profile.html', context)


class CustomPasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'change_password.html'
    success_url = '/'

    def form_valid(self, form):
        messages.success(self.request,
                         'Your password has been changed successfully!')
        return super().form_valid(form)


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "registration/reset/password_reset_subject.txt"
                    c = {
                        "email": user.username,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject,
                                  email,
                                  'admin@example.com', [user.username],
                                  fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("password_reset_done")
    password_reset_form = PasswordResetForm()
    return render(request=request,
                  template_name="registration/reset/password_reset_form.html",
                  context={"form": password_reset_form})

users/templates/change_password.html
{% extends 'reset.html' %} {% load crispy_forms_tags %} {% block title %}Change
Password Page{% endblock title %} {% block content %}

<div class="container form-container-two">
  <h2>Change Password</h2>
  <form method="POST">
    {% csrf_token %} {{ form|crispy }}
    <a href="{% url 'main:chat_list' %}" class="btn btn-danger">Back</a>
    <button class="btn btn-success" style="margin-left: 2%" type="submit">
      Submit
    </button>
  </form>
</div>
{% endblock content %}

users/templates/edit_profile.html
{% extends 'main.html' %} {% load static %} {% block content %}
 {% load crispy_forms_tags %}
<link rel="stylesheet" href="{% static 'css/floating-labels.css' %}" />

<div
  class="container edit-profile-container"
  style="padding: 1.5rem; margin-top: 3%; margin-bottom: 5%; color: white"
>
  <h1 style="text-align: center">
    Edit Profile - <i style="color: blue">ChatsApp</i>
  </h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form %}
    <div class="form-label-group">
      {{field}}
      <label>{{field.label}}</label>
    </div>

    {% endfor %}
    <div class="image-container row">
      <div class="col-12 col-md-6">
        <div class="row">
          <div class="col-12 col-xl-6">
            <label for="file_photo">
              <pre class="🐇">Choose Profile Picture:   </pre>
            </label>
          </div>
          <div class="col-12 col-xl-6">
            <input
              class="form-control"
              type="file"
              id="file_photo"
              onchange="preview_image(event)"
              name="profile_picture"
              required
            />
          </div>
        </div>
      </div>
      <div
        id="camera_icon"
        class="camera_icon col-md-6 col-12"
        style="background-color: purple"
      ></div>
    </div>
    <input type="submit" class="btn btn-success" value="Update" name="" id="" />
    <a
      class="btn btn-danger"
      style="margin-left: 5%"
      href="{% url 'users:user_profile' %}"
      >Back</a
    >
  </form>
</div>

<script>
  camera_icon = document.getElementById("camera_icon");
  document.onload((camera_icon.style.display = "none"));
  function preview_image(event) {
    var reader = new FileReader();
    reader.onload = function () {
      var output = document.getElementById("camera_icon");
      output.style.display = "block";
      output.style.backgroundImage = "url('" + reader.result + "')";
    };
    reader.readAsDataURL(event.target.files[0]);
  }
</script>

{% endblock %}

users/templates/login.html
{% extends 'main.html' %} {% load static %} {% block content %} 
{% load crispy_forms_tags %}
<link rel="stylesheet" href="{% static 'css/floating-labels.css' %}" />

<div
  class="container login-inside"
  style="padding: 5%;border-radius: 15px;"
>
 
    
    <div ><h1 style="margin-left: 35%; margin-bottom: 5%">Sign In - <i style="color: blue;">ChatsApp</i></h1></div>
    
    {% if messages %}
    <div >
  <ul class="messages" style="padding:0 3.5%;" >
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  </div>
  {% endif %}

    <form action="" method="POST">
      {% csrf_token %} {% for field in form %}
      <div class="form-label-group">
        {{field}}
        <label>{{field.label}}</label>
      </div>

      {% endfor %}
      <p style="margin-bottom: 1rem">
        New to <strong style="color: blue"><i>ChatsApp?</i></strong
        ><a href="{% url 'users:register' %}">
          <strong><u>Sign Up</u></strong></a
        >
      </p>
      <input type="submit" value="Login" class="btn btn-success" />
      <p style="margin-top: 1rem; font-size: medium">
        <a
          style="color: rgb(15, 32, 189); text-decoration: underline"
          href="{% url 'users:password-reset' %}"
          ><strong>I have forgotten my password</strong></a
        >
      </p>
    </form>
  

  </div>

  {% endblock content %}

users/templates/register.html
{% extends 'main.html' %} 
{% load crispy_forms_tags %} 
{% block content %}

<div
  class="container form-container register-inside"
  style="padding: 1.5rem; margin-top: 3%; margin-bottom: 5%"
>
  <h1 style="text-align: center">
    Register - <i style="color: blue">ChatsApp</i>
  </h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{form | crispy}}
    <div class="image-container row">
      <div class="col-12 col-md-6">
        <div class="row">
          <div class="col-12 col-xl-6">
            <label for="file_photo">
              <pre>Choose Profile Picture:   </pre>
            </label>
          </div>
          <div class="col-12 col-xl-6">
            <input
              class="form-control"
              type="file"
              id="file_photo"
              onchange="preview_image(event)"
              name="profile_picture"
              required
            />
          </div>
        </div>
      </div>
      <div
        id="camera_icon"
        class="camera_icon col-md-6 col-12"
        style="background-color: purple"
      ></div>
    </div>
    <p
      style="
        margin-bottom: 1rem;
        margin-top: 2rem;
        font-weight: 600;
        font-size: large;
        color: blue;
      "
    >
      Created an account before?<a href="{% url 'users:login' %}"> Sign In</a>
    </p>
    <input type="submit" value="Register" class="btn btn-success" />
  </form>
</div>

<script>
  camera_icon = document.getElementById("camera_icon");
  document.onload((camera_icon.style.display = "none"));

  function preview_image(event) {
    var reader = new FileReader();
    reader.onload = function () {
      var output = document.getElementById("camera_icon");
      output.style.display = "block";
      output.style.backgroundImage = "url('" + reader.result + "')";
    };
    reader.readAsDataURL(event.target.files[0]);
  }
</script>

{% endblock %}

users/templates/reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ChatsApp</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/floating-labels.css' %}" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Password Reset</title>

    <style>
      .form-container-two {
        margin-top: 5%;
      }
    </style>
  </head>

  <body
    style="
      background-image: url('/../static/images/password_change.jpg');
      background-size: cover;
      background-repeat: no-repeat;
    "
  >
    {% block content %} {% endblock %}
  </body>
</html>

users/templates/user_profile.html
{% extends 'main.html' %} {% block content %}

<div class="profile-container">
  <div class="container pc-2">
    <div>
      <img
        class="user-profile-pic"
        id="user-profile-pic"
        src="{{pic}}"
        alt="{{pic}}"
      />
    </div>
    <div class="info">
      <p style="margin-bottom: 0">{{request.user.username}}</p>
      <p>@{{request.user.email}}</p>
    </div>
    <a
      href="{% url 'users:edit_profile' %}"
      class="btn btn-info edit-profile"
      >EDIT PROFILE</a
    >
    <div class="user-info">
      <p style="color: white">Number of chats: {{chat_number}}</p>
      <p style="color: white">
        Total messages: {{request.user.message_set.all.count}}
      </p>
    </div>
  </div>
</div>
{% endblock %}