ChatsApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/reset/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *



app_name = 'main'

urlpatterns = [
    path('', chat_list, name='chat_list'),
    path('chat/<int:pk>/', chat, name='chat'), 
    path('delete_chat/<int:pk>/', delete_chat, name='delete_chat'),
    path('delete_message/<int:pk>/', delete_message, name='delete_message'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login', loginUser, name='login'),
    path('logout', logoutUser, name='logout'),
    path('register', register, name='register'),
    path('user_profile', user_profile, name='user_profile'),
    path('edit_profile', edit_profile, name='edit_profile'),
    path("password-reset/", password_reset_request, name="password-reset"),
    path('change-password/',
         CustomPasswordChangeView.as_view(),
         name='change_password'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
import datetime


# Create your models here.
class User(AbstractUser):
    username = models.CharField(unique=True,
                             max_length=200,
                             null=True,
                             verbose_name='username')
    email = models.EmailField(unique=True,
                                 max_length=200,
                                 verbose_name='email address')
    profile_picture = models.ImageField(default='images/avatar.svg',
                                        upload_to='images/',
                                        null=True,
                                        blank=True)
    is_online = models.BooleanField(default=False)
    last_seen = models.DateTimeField(null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def read_message(self, message) -> None:
        if self.username == message.chat.user:
            message.read = True
        else:
            message.read1 = True
        message.save()

    def __str__(self) -> str:
        return self.username


class ChatManager(models.Manager):

    def create(self, **kwargs):
        user = kwargs['user']
        user1 = kwargs['user1']
        test = Chat.objects.filter(user=user, user1=user1)
        test1 = Chat.objects.filter(user=user1, user1=user)
        if test.exists()  or test1.exists() > 0:
            raise ValidationError('This chat already exists')
        elif not User.objects.filter(
                username=user).exists() or not User.objects.filter(
                    username=user1).exists():
            raise ValidationError(
                'One or both users are not registered on ChatsApp')
        else:
            return super().create(**kwargs)


class Chat(models.Model):
    user = models.CharField(max_length=200)
    user1 = models.CharField(max_length=200)

    def get_other(self, request):
        user_list = [self.user, self.user1]
        return user_list[user_list.index(request.user.username) - 1]

    def user_unread(self):
        user = User.objects.get(username=self.user1)
        return self.messages.filter(read=False, user=user).count()

    def user1_unread(self):
        user = User.objects.get(username=self.user)
        return self.messages.filter(read1=False, user=user).count()

    def get_last_message(self):
        return self.messages.all().last()

    other = None
    other_pic = None
    user_unread_ = None

    def __str__(self) -> str:
        return f"{self.user} | {self.user1}"

    objects = ChatManager()


class Message(models.Model):
    body = models.TextField()
    chat = models.ForeignKey(Chat,
                             on_delete=models.CASCADE,
                             related_name='messages')
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    read = models.BooleanField(null=True, default=False)
    read1 = models.BooleanField(null=True, default=False)
    is_deleted = models.BooleanField(default=False)

    message_margin = '20px'

    def get_user(self):
        return self.chat.user

    def get_user1(self):
        return self.chat.user1

    def __str__(self) -> str:
        if len(self.body) <= 50:
            return self.body
        elif len(self.body) > 50:
            return f"{self.body[:20]}..."

main/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib import messages
from django.http import HttpResponseRedirect


# Create your views here.
def chat_list(request):
    if not request.user.is_authenticated:
        return redirect('users:login')

    user = request.user
    user.is_online = True
    user.save()

    if request.method == 'POST':
        username = request.POST.get('username')
        if username:
            if username == request.user.username:
                messages.error(request,
                               "Can't create a chat with your username")
            elif not User.objects.filter(username=request.user.username
                                         ).exists() or not User.objects.filter(
                                             username=username).exists():
                messages.error(request,
                               'This user is not registered on ChatsApp')
            else:
                try:
                    Chat.objects.create(user=request.user.username,
                                        user1=username)
                    messages.success(
                        request,
                        f'The chat "{username}" was added successfully!')
                except ValidationError:
                    messages.error(request, 'This chat already exists')
    all_chats = Chat.objects.all()
    chats = [
        chat for chat in all_chats
        if request.user.username in [chat.user, chat.user1]
    ]
    sorted_chats = []
    null_chats = []
    unread_chats_count = 0
    for chat in chats:
        chat.other = chat.get_other(request)
        if chat.user1 == request.user.username:
            chat.user_unread_ = chat.user1_unread()
        else:
            chat.user_unread_ = chat.user_unread()
        chat.save()
        if chat.user_unread_:
            unread_chats_count += 1
        chat.other_pic = User.objects.get(
            username=chat.other).profile_picture.url
    sorted_chats = []
    for chat in chats:
        if chat.messages.all().count() == 0:
            chats.remove(chat)
            null_chats.append(chat)
    while len(chats) > 0:
        for chat in chats:
            if chat.messages.all().count() != 0:
                passed = True
                #   check if it is the most recent
                for comparison in chats:
                    if chat.get_last_message(
                    ).created >= comparison.get_last_message().created:
                        continue
                    else:
                        passed = False
                        break
                if passed:
                    sorted_chats.append(chat)
                    chats.remove(chat)
                    break
            elif chat.get_last_message() is None:
                null_chats.append(chat)
    if unread_chats_count:
        label = f'Chats ({unread_chats_count})'
    else:
        label = 'Chats'
    chats = sorted_chats + null_chats
    context = {'chats': chats, 'label': label}
    return render(request, 'chat_list.html', context)


def chat(request, pk):
    user = request.user
    chat = Chat.objects.get(id=pk)

    friend = chat.user1
    if request.user.username == chat.user1:
        friend = chat.user

    if request.method == 'POST':
        message = request.POST.get('message')
        if message:
            Message.objects.create(body=message, chat=chat, user=user)

    messages = chat.messages.all()
    message_list = []
    for message in messages:
        user.read_message(message)
        message.save()
        message_list.append(message)

    for message in message_list:
        if message_list.index(message) + 1 != len(
                message_list) and message_list[message_list.index(message) +
                                               1].user == message.user:
            message.message_margin = '0px'
        pass

    friend = User.objects.get(username=friend)
    if friend.is_online:
        online_status = 'online'
    else:
        online_status = f'last seen on {friend.last_seen}'

    context = {
        'friend': friend,
        'messages': messages,
        'online_status': online_status
    }
    return render(request, 'chat.html', context)


def delete_chat(request, pk):
    chat = Chat.objects.get(id=pk)
    message_count = chat.messages.count()
    message = ' and one message'
    chat_name = chat.get_other(request)

    if message_count > 1:
        message = f' and all its {message_count} messages'
    elif not message_count:
        message = ''

    if request.method == 'POST':
        chat.delete()
        messages.success(request,
                         f'The chat "{chat_name}" was deleted successfully!')
        return redirect('main:chat_list')
    return render(request, 'delete.html', {'message': message})


def delete_message(request, pk):
    message = Message.objects.get(pk=pk)
    prim_key = message.chat.id
    if request.user != message.user:
        return redirect('main:chat', prim_key)
    message.body = 'This message was deleted'
    message.is_deleted = True
    message.save()
    # return HttpResponseRedirect(request.META.get('HTTP_REFERER')) -> To basically return
    # to the same page without explicitly spelling out what that page is.
    # Explicitly deleting from the address bar will raise a 'Page not found (404)' error.
    return redirect('main:chat', prim_key)
    # => In the case of an explicit address-bar-deletion,
    # the user will be redirected to the chat page to see the effect of that deletion (Intentional).
    # And also to avoid 404 errors.

main/templates/chat.html
{% extends 'main.html' %} {% load static %} {% block content %}
<div
  class="container-lg"
  style="
    border: 3px solid aqua;
    background-image: url('/../static/images/flowers.jpg');
    background-size: cover;
    position: sticky;
    height: 95vh;
  "
>
  <div class="other-profile row">
    <a
      href="{% url 'main:chat_list' %}"
      class="col-1 btn btn-success"
      style="padding: 0; height: 25px; margin-top: 10px"
      href=""
      ><p><strong>&LongLeftArrow;</strong></p></a
    >

    <div class="col-sm-1 col-2">
      <div class="row" style="height: 40px">
        <div
          class="col-sm-10 offset-1 col-10 offset-md-4 col-md-8 col-lg-5 offset-lg-7 other-profile-2"
          style="background-image: url({{friend.profile_picture.url}});"
        ></div>
      </div>
    </div>
    <div class="col-8 col-lg-10">
      <div class="row">
        <div class="col-sm-10 col-md-10 col-9">
          <h6 style="color: white; margin: 0">{{friend}}</h6>
          <div
            style="
              display: flex;
              align-items: center;
              overflow-x: auto;
              margin-top: 0;
              color: aqua;
            "
          >
            {{friend.email}} ({{online_status}})
          </div>
        </div>

        <div class="col-sm-2 col-lg-1 col-3">
          <div class="row" style="height: 40%">
            <a
              href=""
              class="col-6 col-sm-5 btn refresh"
              style="background-color: rgb(0, 204, 255); padding: 0"
            >
              ↻
            </a>

            <div
              class="col-5 offset-sm-2 btn-success time-format"
              style="
                display: flex;
                align-items: center;
                justify-content: center;
                padding: 0;
                border-radius: 5px;
              "
            >
              <img
                style="width: 15px; height: 15px"
                src="{% static 'images/time-format.png' %}"
                alt=""
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="messages-container">
    {% for message in messages %} {% if message.user == request.user %}
    <!-- MY MESSAGE -->
    <div class="row" style="flex-direction: row-reverse;">
      <div class="style" style="display: none">{{message.message_margin}}</div>
      <div class="mine " style="max-width: 50%;width: fit-content;">
        <div style="display: flex; flex-direction: row">
          <div style="width: 100%">
            <div class="message-body">{{message.body}}</div>
            {% if not message.is_deleted %}
            <small
              class="rawtimes"
              style="font-size: xx-small; color: blueviolet"
              ><p>{{message.created}}</p></small
            >
            <small
              class="timesinces"
              style="font-size: xx-small; color: blueviolet; display: none"
              >{{message.created|timesince}} ago</small
            >
            
          </div>

          <div class="dropdown dropup" style="width: 3%">
            <div
              class=""
              style="width: fit-content"
              type="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <strong>&#8942;</strong>
            </div>
            <ul class="dropdown-menu" style="padding: 0;">
              <li><a class="btn btn-danger" style="width: 100%;height:100%" href="{% url 'main:delete_message' message.id %}">Delete</a></li>
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- MY MESSAGE ENDS -->
    {% else %}

    <!-- OTHER MESSAGE -->
    <div class="row">
      <div class="style" style="display: none">{{message.message_margin}}</div>
      <div class="other mine " style="max-width: 50%;width: fit-content;">
        <div class="message-body">{{message.body}}</div>
        {% if not message.is_deleted %}
        <small class="rawtimes" style="font-size: xx-small; color: blueviolet"
          ><p>{{message.created}}</p></small
        >
        <small
          class="timesinces"
          style="font-size: xx-small; color: blueviolet; display: none"
          >{{message.created|timesince}} ago</small
        >
        {% endif %}
      </div>
    </div>
    <!-- OTHER MESSAGE ENDS -->
    {% endif %} {% endfor %}

    <div class="message-input">
      <form action="" class="row" method="POST">
        {% csrf_token %}
        <input
          id="input"
          class="col-lg-6 offset-lg-5 col-md-7 offset-md-4 col-10 offset-sm-1"
          type="text"
          name="message"
          placeholder="Write new message..."
          autofocus
        />
        <input
          class="col-lg-1 col-2 col-sm-2 col-md-3 btn"
          style="
            background-image: url('/../static/images/send.png');
            background-size: contain;
            background-repeat: no-repeat;
            border: 2px solid blue;
            width: fit-content;
            padding: 13px;
            background-color: white;
          "
          type="submit"
          value=""
        />
      </form>
    </div>
  </div>
</div>

<script>
  var message_body = document.querySelectorAll('.message-body');
  var msg_container = document.querySelector(".messages-container");
  msg_container.scrollTo(0, msg_container.scrollHeight);

  var timesinces = document.querySelectorAll(".timesinces");
  var rawtimes = document.querySelectorAll(".rawtimes");
  var time_format = document.querySelector(".time-format");
  var refresh = document.querySelector(".refresh");
  var styles = document.querySelectorAll(".style");

  for (element of styles) {
    element.nextElementSibling.style.marginBottom = element.innerText;
  }

  time_format.addEventListener("click", function () {
    if (timesinces[0].style.display == "none") {
      for (timesince of timesinces) {
        timesince.style.display = "block";
      }
      for (rawtime of rawtimes) {
        rawtime.style.display = "none";
      }
    } else {
      for (timesince of timesinces) {
        timesince.style.display = "none";
      }
      for (rawtime of rawtimes) {
        rawtime.style.display = "block";
      }
    }
  });

  for(element of message_body){
    console.log(element.innerText);
    if(element.innerText === 'This message was deleted')
    {
    element.style.fontStyle = 'italic';
    element.style.fontSize = '0.7rem';
    element.style.textAlign = 'center'
  }
  }
  console.log(message_body);
</script>
{% endblock %}

main/templates/chat_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChatsApp</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div style="
width:100vw;
height:100vh;
background-image: url('../static/images/login.jfif');
background-size: cover;
overflow-y: auto;
">

<div class="container-lg box" style="margin-top: 5%;margin-bottom:10%">
  <div
    class="row" 
    style="
      border: 2px solid rgb(47, 0, 255);
      border-radius: 20px;
      background-color: red;
      margin-bottom: 2vh;
      min-width: fit-content;
      
    "
  >
    <div
      class="col-xs-12 col-sm-2"
      style="display: flex; align-items: center; justify-content: center"
    >
      <img class="user-profile-pic" src="{{request.user.profile_picture.url}}" alt="" />
    </div>
    <div class="col-xs-12 col-sm-10">
      <div class="row">
        <div class="col-9 col-xl-10 col-md-9">
          <div>
            <h1 style="color: white">{{request.user.username}}</h1>
            <p style="color: white">{{request.user.email}}</p>
          </div>
        </div>

        <div
          class="col-3 col-xl-2 col-md-3"
          style="display: flex; align-items: center; justify-content: center"
        >
          <div class="row">
            <div class="col-12" style="border: 2px solid aqua;border-radius: 10px;">
                <div class="btn-group">
                  <div class="btn btn-more btn-sm light-blue-hover" type="button" data-bs-toggle="dropdown" data-bs-auto-close="outside"
                    aria-expanded="false">
                    <strong style="font-size: 1.5rem;">. . .</strong>
                </div>
                  <ul class="dropdown-menu">
                    <li>
          
                      <div class="dropdown dropstart ">
                        <button style="width: 100%;" type="button" class="btn btn-primary" data-bs-toggle="dropdown"
                          aria-expanded="false" data-bs-auto-close="outside">
                          &ShortLeftArrow; Add new chat
                        </button>
                        <form class="dropdown-menu p-4"style="width: 10%;" method="POST">
                          {% csrf_token %}
                          <div class="mb-3" >
                            <label for="username" class="form-label">Username:</label>
                            <input type="text" class="form-control" name="username" id="username" placeholder="">
                          </div>
                          <button type="submit" class="btn btn-primary">Add</button>
                        </form>
                      </div>
          
                    </li>
                    <li><a class="dropdown-item" href="{% url 'users:user_profile' %}">My Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:change_password' %}">Change Password</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                  </ul>
                </div>
          
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  
 
<div class="">
 <div  class="row">
    <a href="" class="btn chats-label col-12 col-sm-3" style="background-color: blue; ">
      {{label}}
    </a>
</div>

<div class="row" >
     {% for chat in chats %}
      <div class="col-12">
        <div class="row chat-row">
          <a href="{% url 'main:chat' chat.id %}" class="col-6 col-md-8" style="background-color: white; padding: 2%;color:black">


            <div style="display: flex;flex-direction: row;">
                <img style="height: 50px;width:50px" class="user-profile-pic" src="{{chat.other_pic}}" alt="{{chat.other_pic}}">
                <div style="margin-left:2%;overflow-x:auto;">
            <div class="fw-bold"><strong>{{chat.other}}</strong></div>
            {% if chat.get_last_message is not None %}
            {% if chat.get_last_message.user == request.user %}
            {% if chat.get_last_message.user.username == chat.user and chat.get_last_message.read1 %}
            <small style="font-size: 0.6rem;color: rgb(0, 119, 255)"><strong><em>&#x2713;&#x2713;</em></strong></small>
            {% elif chat.get_last_message.user.username == chat.user1 and chat.get_last_message.read %}
            <small
              style="font-size: 0.6rem;color: rgb(0, 119, 255)"><strong><em>&#10003;&#10003;</em></strong></small>
            {% else %}
            <small style="font-size: 0.6rem;"><strong><em>&#10003;&#10003;</em></strong></small>
            {% endif %}
            {% endif %}
            {{chat.get_last_message}}
            {% endif %}
        </div>
        </div>
          </a>
          
          <div class=" col-6 col-md-4" style="background-color:white">
            <div class="row" style="padding: 0;">
             <a href="{% url 'main:chat' chat.id %}" class="col-10" style="display: flex;flex-direction:column;margin: 0;align-items: center;margin-top: 5%;">
              {% if chat.user_unread_ %}
              <span class="badge bg-primary rounded-pill"
                style="font-size: large; color: white;width:fit-content;margin: auto;">{{chat.user_unread_}}</span>
              {% endif %}
              {% if chat.get_last_message is not None %}
              <span class="badge now-factor">{{chat.get_last_message.created|timesince}} ago</span>
              {% endif %}
            </a>
            <div class="col-2" style="padding:0;margin-top: 30px;">
                <a href="{% url 'main:delete_chat' chat.id %}">
                    <img style="margin-top: 20%;width: 20px;height: 20px;" src="{% static 'images/delete.png' %}"  alt="Delete icon">
                </a>
            </div>
        </div>
    </div>      
</div>
        </div>
      {% endfor %}
    </div>
</div>

</div>
</div>
</body>
</html>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.6.1.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/js.js' %}"></script>

main/templates/delete.html
{% extends 'main.html' %} {% block content %}

<div class="container">
  <div class="del-container">
    <form action="" method="POST">
      {% csrf_token %}
      <p>
        <strong
          >Are you sure you want to delete this chat{{message}}? This action
          cannot be undone!</strong
        >
      </p>
      <input
        type="submit"
        class="btn btn-danger"
        style="margin-right: 10%; margin-left: 30%"
        value="Yes, I'm sure"
      />
      <a href="/" class="btn btn-success">No, take me back</a>
    </form>
  </div>
</div>

{% endblock %}

main/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ChatsApp</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>

  <body>
    {% block content %} {% endblock %}
  </body>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.6.1.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/js.js' %}"></script>
</html>